version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:800979273128:task-definition/auditseverity:1"
        LoadBalancerInfo:
          ContainerName: "auditseverity"
          ContainerPort: 9200